/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day32;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.driver.OracleDriver;

/**
 *
 * @author 1027
 */
public class Day32 extends javax.swing.JFrame {

    /**
     * Creates new form Ex01
     */
    public Day32() {
        initComponents();
        myinitComponents();
    }
    private void myinitComponents(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel1 = new java.awt.Panel();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        label1 = new java.awt.Label();
        panel4 = new java.awt.Panel();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label5 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label6 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        label7 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        button9 = new java.awt.Button();
        button1 = new java.awt.Button();
        panel5 = new java.awt.Panel();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new java.awt.GridLayout(5, 0, 10, 5));

        button2.setLabel("보기");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel1.add(button2);

        button3.setLabel("입력");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panel1.add(button3);

        button4.setLabel("수정");
        panel1.add(button4);

        button5.setLabel("삭제");
        panel1.add(button5);

        button6.setLabel("종료");
        panel1.add(button6);

        getContentPane().add(panel1, java.awt.BorderLayout.LINE_END);

        panel2.setBackground(new java.awt.Color(255, 0, 51));

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 255));
        label2.setText("성적관리프로그램");
        panel2.add(label2);

        getContentPane().add(panel2, java.awt.BorderLayout.PAGE_START);

        label1.setText("환영합니다");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel3, java.awt.BorderLayout.CENTER);

        panel4.setVisible(false);
        panel4.setLayout(new java.awt.GridLayout(6, 2, 0, 30));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setText("학번");
        panel4.add(label3);
        panel4.add(textField1);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setText("이름");
        panel4.add(label4);
        panel4.add(textField2);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setText("국어");
        panel4.add(label5);
        panel4.add(textField3);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setText("영어");
        panel4.add(label6);
        panel4.add(textField4);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setText("수학");
        panel4.add(label7);
        panel4.add(textField5);

        button9.setLabel("입력");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        panel4.add(button9);

        button1.setLabel("취소");
        panel4.add(button1);

        getContentPane().add(panel4, java.awt.BorderLayout.CENTER);

        panel5.setVisible(false);

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        panel5.add(list1);

        getContentPane().add(panel5, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 416, 392);
    }// </editor-fold>                        

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.out.println("버튼 클릭");
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
        panel4.setVisible(true);
        this.revalidate();//
    }                                       

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String num=textField1.getText();
        String name="\'"+textField2.getText()+"\'";
        String kor =textField3.getText();
        String eng =textField4.getText();
        String math=textField5.getText();
        String sql ="insert into stu02 values (";
        sql+=num+",";
        sql+=name+",";
        sql+=kor+",";
        sql+=eng+",";
        sql+=math+")";
//        String sql ="update stu02 set name=";
//        sql+=name+",kor=";
//        sql+=kor+",eng=";
//        sql+=eng+",math=";
//        sql+=math+" where num="+num;
//        System.out.println(sql);
        dbUpdate(sql);
    }                                       

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
        panel5.setVisible(true);
        this.revalidate();
        String sql ="select * from stu02";
        dbSelect(sql);
        System.out.println(sql);
    }                                       

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     
    public void dbSelect(String sql){
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        String id="scott";
        String pw="tiger";
        Connection conn = null;
        Statement stmt=null;
        ResultSet rs=null;
        try {
            //        new oracle.jdbc.driver.OracleDriver();
            //        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection(url,id,pw);
            stmt = conn.createStatement();
            rs=stmt.executeQuery(sql);
            while(rs.next()){
                int num =rs.getInt("num");
                String name = rs.getString("name");
                int kor = rs.getInt("kor");
                int eng = rs.getInt("eng");
                int math = rs.getInt("math");
                String itm =num+"/"+name+"/"+kor+"/"+eng+"/"+math;
                System.out.println(itm);
                list1.addItem(itm);
            }
        }catch(Exception e){
            System.out.println("입력 오류"+e.getMessage());
        } finally {
            try {
                if(rs!=null)rs.close();
                if(stmt!=null)stmt.close();
                if(conn!=null)conn.close();
            } catch (SQLException ex) {
            }
        }
    }
    public void dbUpdate(String sql){
        String url="jdbc:oracle:thin:@localhost:1521:xe";
        String id="scott";
        String pw="tiger";
        Connection conn = null;
        Statement stmt=null;
        try {
            //        new oracle.jdbc.driver.OracleDriver();
            //        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection(url,id,pw);
            stmt = conn.createStatement();
            stmt.executeUpdate(sql);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        } finally {
            try {
                if(stmt!=null)stmt.close();
                if(conn!=null)conn.close();
            } catch (SQLException ex) {
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel aaa*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day32().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.List list1;
    public java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    // End of variables declaration                   
}
